
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace StatisticsOfSales_v2.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Client
{

    public Client()
    {

        this.Sales = new HashSet<Sale>();

    }


    public int ClientID { get; set; }

    public string ClientName { get; set; }



    public virtual ICollection<Sale> Sales { get; set; }

}

}
