
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace StatisticsOfSales_v2.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Sale
{

    public int SaleID { get; set; }

    public int ManagerID { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

    public int ClientID { get; set; }

    public int ProductID { get; set; }

    public Nullable<decimal> TotalSum { get; set; }



    public virtual Client Client { get; set; }

    public virtual Manager Manager { get; set; }

    public virtual Product Product { get; set; }

}

}
